[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://doctovoiceweb-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/outputs/*"
  to = "https://doctovoiceweb-production.up.railway.app/outputs/:splat"
  status = 200
  force = true
